export const categories = [
  {
    name: "Men",
    image: "/images/product_7.png",
  },
  {
    name: "Women",
    image: "/images/product_18.png",
  },
  {
    name: "Kids",
    image: "/images/product_27.png",
  },
  {
    name: "Electronics",
    image: "/images/product_38.png",
  },
  {
    name: "Cosmetics",
    image: "/images/product_50.png",
  },
]

export const all_products = [
  // Products
  {
    id: "1",
    name: "Elegant Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    image: "/images/product_1.png",
    price: 120.0,
    rating: 4.5,
    reviews: 10,
    description: "Elevate your style with our elegant and chic blouse, featuring flutter sleeves and a peplum hem.",
    category: "Men",
  },
  {
    id: "2",
    name: "Stylish Floral Print Summer Dress with Belt and V Neck Design",
    image: "/images/product_2.png",
    price: 180.0,
    rating: 4.5,
    reviews: 5,
    description: "Step into summer with our Floral Print Summer Dress, tailored for comfort and sophistication.",
    category: "Men",
  },
  {
    id: "3",
    name: "Sophisticated Double Breasted Longline Blazer",
    image: "/images/product_3.png",
    price: 160.0,
    rating: 4.5,
    reviews: 7,
    description: "Embrace elegance and versatility with our Women's Blazer, perfect for day to night transitions.",
    category: "Men",
  },
  {
    id: "4",
    name: "Classic Double Breasted Belted Trench Coat",
    image: "/images/product_4.png",
    price: 200.0,
    rating: 4.5,
    reviews: 12,
    description: "Stay stylishly warm with our Trench Coat, designed to complement your sophisticated urban look.",
    category: "Men",
  },
  {
    id: "5",
    name: "Fashionable High Waist A Line Midi Skirt with Button Detail",
    image: "/images/product_5.png",
    price: 250.0,
    rating: 4.5,
    reviews: 8,
    description:
        "Add flair to your wardrobe with our Skirt, crafted for the modern woman who loves contemporary fashion.",
    category: "Men",
  },
  {
    id: "6",
    name: "Chic Handbag with Gold Hardware and Removable Strap",
    image: "/images/product_6.png",
    price: 140.0,
    rating: 4.5,
    reviews: 9,
    description: "Complete your look with our Handbag, designed to be both stylish and functional for everyday use.",
    category: "Men",
  },
  {
    id: "7",
    name: "Elegant Pointed Toe Stiletto Heels with Ankle Strap",
    image: "/images/product_7.png",
    price: 180.0,
    rating: 4.5,
    reviews: 11,
    description: "Step out in confidence with our Heels, crafted for comfort and style to elevate your every step.",
    category: "Men",
  },
  {
    id: "8",
    name: "Stylish Hooded Winter Coat with Faux Fur Trim",
    image: "/images/product_8.png",
    price: 150.0,
    rating: 4.5,
    reviews: 15,
    description:
        "Stay warm and stylish with our Winter Coat, crafted for the modern woman who values both fashion and function.",
    category: "Men",
  },
  {
    id: "9",
    name: "Chic Wide Leg Jumpsuit with Sleeveless Design",
    image: "/images/product_9.png",
    price: 280.0,
    rating: 4.5,
    reviews: 12,
    description: "Make a statement with our Jumpsuit, perfect for the confident woman who loves contemporary fashion.",
    category: "Men",
  },
  {
    id: "10",
    name: "Fashionable Silk Scarf with Floral Print",
    image: "/images/product_10.png",
    price: 180.0,
    rating: 4.5,
    reviews: 14,
    description: "Complete your look with our Scarf, designed to add a touch of elegance to any outfit.",
    category: "Men",
  },
  {
    id: "11",
    name: "Elegant Pointed Toe Pumps with Kitten Heel",
    image: "/images/product_11.png",
    price: 80.0,
    rating: 4.5,
    reviews: 10,
    description: "Step out in style with our Pumps, crafted for both comfort and sophistication.",
    category: "Men",
  },
  {
    id: "12",
    name: "Classic Fit Two Button Wool Blend Suit",
    image: "/images/product_12.png",
    price: 240.0,
    rating: 4.5,
    reviews: 16,
    description:
        "Make a statement of bold elegance with our Suit, perfect for those who appreciate fashion that speaks volumes.",
    category: "Men",
  },

  // Women's Products
  {
    id: "13",
    name: "Green Solid Zippered Full Zip Slim Fit Bomber Jacket",
    image: "/images/product_13.png",
    price: 180.0,
    rating: 4.5,
    reviews: 10,
    description:
        "Discover the perfect blend of comfort and style with our Bomber Jacket, designed for the contemporary woman.",
    category: "Women",
  },
  {
    id: "14",
    name: "Casual Denim Shirt with Button Down Front and Chest Pockets",
    image: "/images/product_14.png",
    price: 160.0,
    rating: 4.5,
    reviews: 8,
    description:
        "Embrace casual charm with our Denim Shirt, tailored for the modern woman who values comfort and style.",
    category: "Women",
  },
  {
    id: "15",
    name: "Classic Polo Shirt with Contrast Collar and Cuffs",
    image: "/images/product_15.png",
    price: 120.0,
    rating: 4.2,
    reviews: 15,
    description: "A timeless classic with modern touches, perfect for casual and semi-formal occasions.",
    category: "Women",
  },
  {
    id: "16",
    name: "Chic Handbag with Gold Hardware and Removable Strap",
    image: "/images/product_16.png",
    price: 140.0,
    rating: 4.5,
    reviews: 9,
    description: "Complete your look with our Handbag, designed to be both stylish and functional for everyday use.",
    category: "Women",
  },
  {
    id: "17",
    name: "Elegant Pointed Toe Stiletto Heels with Ankle Strap",
    image: "/images/product_17.png",
    price: 180.0,
    rating: 4.5,
    reviews: 11,
    description: "Step out in confidence with our Heels, crafted for comfort and style to elevate your every step.",
    category: "Women",
  },
  {
    id: "18",
    name: "Stylish Hooded Winter Coat with Faux Fur Trim",
    image: "/images/product_18.png",
    price: 150.0,
    rating: 4.5,
    reviews: 15,
    description:
        "Stay warm and stylish with our Winter Coat, crafted for the modern woman who values both fashion and function.",
    category: "Women",
  },
  {
    id: "20",
    name: "Fashionable Silk Scarf with Floral Print",
    image: "/images/product_20.png",
    price: 180.0,
    rating: 4.5,
    reviews: 14,
    description: "Complete your look with our Scarf, designed to add a touch of elegance to any outfit.",
    category: "Women",
  },
  {
    id: "21",
    name: "Elegant Pointed Toe Pumps with Kitten Heel",
    image: "/images/product_21.png",
    price: 80.0,
    rating: 4.5,
    reviews: 10,
    description: "Step out in style with our Pumps, crafted for both comfort and sophistication.",
    category: "Women",
  },
  {
    id: "22",
    name: "Classic Fit Two Button Wool Blend Suit",
    image: "/images/product_22.png",
    price: 240.0,
    rating: 4.5,
    reviews: 16,
    description:
        "Make a statement of bold elegance with our Suit, perfect for those who appreciate fashion that speaks volumes.",
    category: "Women",
  },
]
