import product_1 from "../public/images/product_1.png"
import product_2 from "../public/images/product_2.png"
import product_3 from "../public/images/product_3.png"
import product_4 from "../public/images/product_4.png"
import product_5 from "../public/images/product_5.png"
import product_6 from "../public/images/product_6.png"
import product_7 from "../public/images/product_7.png"
import product_8 from "../public/images/product_8.png"
import product_9 from "../public/images/product_9.png"
import product_10 from "../public/images/product_10.png"
import product_11 from "../public/images/product_11.png"
import product_12 from "../public/images/product_12.png"
import product_13 from "../public/images/product_13.png"
import product_14 from "../public/images/product_14.png"
import product_15 from "../public/images/product_15.png"
import product_16 from "../public/images/product_16.png"
import product_17 from "../public/images/product_17.png"
import product_18 from "../public/images/product_18.png"
import product_19 from "../public/images/product_19.png"
import product_20 from "../public/images/product_20.png"
import product_21 from "../public/images/product_21.png"
import product_22 from "../public/images/product_22.png"

export const categories = [
  {
    name: "Men",
    image: "/images/product_7.png",
  },
  {
    name: "Women",
    image: "/images/product_18.png",
  },
  {
    name: "Kids",
    image: "/images/product_27.png",
  },
  {
    name: "Electronics",
    image: "/images/product_38.png",
  },
  {
    name: "Cosmetics",
    image: "/images/product_50.png",
  },
]

export const all_products = [
  // Products
  {
    index: 0,
    id: "1",
    name: "Elegant Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    image: product_1,
    images: ["/images/product_1.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 120.0,
    originalPrice: 150.0,
    rating: 4.5,
    reviews: 10,
    description: "Elevate your style with our elegant and chic blouse, featuring flutter sleeves and a peplum hem.",
    features: ["Flutter Sleeves", "Overlap Collar", "Peplum Hem", "Lightweight Fabric"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Navy", "Pink", "Black"],
    category: "Men",
    brand: "Trendify",
    sku: "TRF-001",
    inStock: true,
    stockCount: 25,
    isNew: true,
    isSale: true,
  },
  {
    index: 1,
    id: "2",
    name: "Stylish Floral Print Summer Dress with Belt and V Neck Design",
    image: product_2,
    images: ["/images/product_2.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 180.0,
    originalPrice: 220.0,
    rating: 4.5,
    reviews: 5,
    description: "Step into summer with our Floral Print Summer Dress, tailored for comfort and sophistication.",
    features: ["Floral Print", "V Neck Design", "Belt Included", "Summer Weight"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Floral Blue", "Floral Pink", "Floral Yellow"],
    category: "Men",
    brand: "Trendify",
    sku: "TRF-002",
    inStock: true,
    stockCount: 18,
    isNew: true,
    isSale: true,
  },
  {
    index: 2,
    id: "3",
    name: "Sophisticated Double Breasted Longline Blazer",
    image: product_3,
    images: ["/images/product_3.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 160.0,
    originalPrice: 200.0,
    rating: 4.5,
    reviews: 7,
    description: "Embrace elegance and versatility with our Women's Blazer, perfect for day to night transitions.",
    features: ["Double Breasted", "Longline Cut", "Professional Fit", "Structured Shoulders"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Gray", "Burgundy"],
    category: "Men",
    brand: "Trendify",
    sku: "TRF-003",
    inStock: true,
    stockCount: 32,
    isNew: false,
    isSale: true,
  },
  {
    index: 3,
    id: "4",
    name: "Classic Double Breasted Belted Trench Coat",
    image: product_4,
    images: ["/images/product_4.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 200.0,
    rating: 4.5,
    reviews: 12,
    description: "Stay stylishly warm with our Trench Coat, designed to complement your sophisticated urban look.",
    features: ["Double Breasted", "Belted Waist", "Water Resistant", "Classic Collar"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Beige", "Black", "Navy", "Olive"],
    category: "Men",
    brand: "Trendify",
    sku: "TRF-004",
    inStock: true,
    stockCount: 15,
    isNew: true,
    isSale: false,
  },
  {
    index: 4,
    id: "5",
    name: "Fashionable High Waist A Line Midi Skirt with Button Detail",
    image: product_5,
    images: ["/images/product_5.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 250.0,
    originalPrice: 300.0,
    rating: 4.5,
    reviews: 8,
    description:
        "Add flair to your wardrobe with our Skirt, crafted for the modern woman who loves contemporary fashion.",
    features: ["High Waist", "A Line Cut", "Button Detail", "Midi Length"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Burgundy", "Camel"],
    category: "Men",
    brand: "Trendify",
    sku: "TRF-005",
    inStock: true,
    stockCount: 22,
    isNew: false,
    isSale: true,
  },
  {
    index: 5,
    id: "6",
    name: "Chic Handbag with Gold Hardware and Removable Strap",
    image: product_6,
    images: ["/images/product_6.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 140.0,
    rating: 4.5,
    reviews: 9,
    description: "Complete your look with our Handbag, designed to be both stylish and functional for everyday use.",
    features: ["Gold Hardware", "Removable Strap", "Multiple Compartments", "Premium Material"],
    sizes: ["One Size"],
    colors: ["Black", "Brown", "Tan", "Navy"],
    category: "Men",
    brand: "Trendify",
    sku: "TRF-006",
    inStock: true,
    stockCount: 45,
    isNew: true,
    isSale: false,
  },
  {
    index: 6,
    id: "7",
    name: "Elegant Pointed Toe Stiletto Heels with Ankle Strap",
    image: product_7,
    images: ["/images/product_7.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 180.0,
    originalPrice: 220.0,
    rating: 4.5,
    reviews: 11,
    description: "Step out in confidence with our Heels, crafted for comfort and style to elevate your every step.",
    features: ["Pointed Toe", "Stiletto Heel", "Ankle Strap", "Cushioned Insole"],
    sizes: ["6", "7", "8", "9", "10", "11"],
    colors: ["Black", "Nude", "Red", "Navy"],
    category: "Men",
    brand: "Trendify",
    sku: "TRF-007",
    inStock: true,
    stockCount: 28,
    isNew: false,
    isSale: true,
  },
  {
    index: 7,
    id: "8",
    name: "Stylish Hooded Winter Coat with Faux Fur Trim",
    image: product_8,
    images: ["/images/product_8.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 150.0,
    rating: 4.5,
    reviews: 15,
    description:
        "Stay warm and stylish with our Winter Coat, crafted for the modern woman who values both fashion and function.",
    features: ["Hooded Design", "Faux Fur Trim", "Insulated Lining", "Water Resistant"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Gray", "Burgundy"],
    category: "Men",
    brand: "Trendify",
    sku: "TRF-008",
    inStock: true,
    stockCount: 19,
    isNew: true,
    isSale: false,
  },
  {
    index: 8,
    id: "9",
    name: "Chic Wide Leg Jumpsuit with Sleeveless Design",
    image: product_9,
    images: ["/images/product_9.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 280.0,
    originalPrice: 350.0,
    rating: 4.5,
    reviews: 12,
    description: "Make a statement with our Jumpsuit, perfect for the confident woman who loves contemporary fashion.",
    features: ["Wide Leg Cut", "Sleeveless Design", "Belted Waist", "Premium Fabric"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Olive", "Burgundy"],
    category: "Men",
    brand: "Trendify",
    sku: "TRF-009",
    inStock: true,
    stockCount: 14,
    isNew: true,
    isSale: true,
  },
  {
    index: 9,
    id: "10",
    name: "Fashionable Silk Scarf with Floral Print",
    image: product_10,
    images: ["/images/product_10.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 180.0,
    rating: 4.5,
    reviews: 14,
    description: "Complete your look with our Scarf, designed to add a touch of elegance to any outfit.",
    features: ["100% Silk", "Floral Print", "Versatile Styling", "Soft Texture"],
    sizes: ["One Size"],
    colors: ["Floral Blue", "Floral Pink", "Floral Green", "Solid Navy"],
    category: "Men",
    brand: "Trendify",
    sku: "TRF-010",
    inStock: true,
    stockCount: 67,
    isNew: false,
    isSale: false,
  },
  {
    index: 10,
    id: "11",
    name: "Elegant Pointed Toe Pumps with Kitten Heel",
    image: product_11,
    images: ["/images/product_11.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 80.0,
    originalPrice: 100.0,
    rating: 4.5,
    reviews: 10,
    description: "Step out in style with our Pumps, crafted for both comfort and sophistication.",
    features: ["Pointed Toe", "Kitten Heel", "Slip-On Style", "Comfortable Fit"],
    sizes: ["6", "7", "8", "9", "10", "11"],
    colors: ["Black", "Nude", "Navy", "Brown"],
    category: "Men",
    brand: "Trendify",
    sku: "TRF-011",
    inStock: true,
    stockCount: 41,
    isNew: false,
    isSale: true,
  },
  {
    index: 11,
    id: "12",
    name: "Classic Fit Two Button Wool Blend Suit",
    image: product_12,
    images: ["/images/product_12.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 240.0,
    rating: 4.5,
    reviews: 16,
    description:
        "Make a statement of bold elegance with our Suit, perfect for those who appreciate fashion that speaks volumes.",
    features: ["Two Button Style", "Wool Blend", "Classic Fit", "Professional Cut"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Gray", "Charcoal"],
    category: "Men",
    brand: "Trendify",
    sku: "TRF-012",
    inStock: true,
    stockCount: 23,
    isNew: true,
    isSale: false,
  },

  // Women's Products
  {
    index: 12,
    id: "13",
    name: "Green Solid Zippered Full Zip Slim Fit Bomber Jacket",
    image: product_13,
    images: ["/images/product_13.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 180.0,
    originalPrice: 225.0,
    rating: 4.5,
    reviews: 10,
    description:
        "Discover the perfect blend of comfort and style with our Bomber Jacket, designed for the contemporary woman.",
    features: ["Full Zip", "Slim Fit", "Ribbed Cuffs", "Lightweight"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Green", "Black", "Navy", "Burgundy"],
    category: "Women",
    brand: "Trendify",
    sku: "TRF-013",
    inStock: true,
    stockCount: 35,
    isNew: true,
    isSale: true,
  },
  {
    index: 13,
    id: "14",
    name: "Casual Denim Shirt with Button Down Front and Chest Pockets",
    image: product_14,
    images: ["/images/product_14.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 160.0,
    originalPrice: 200.0,
    rating: 4.5,
    reviews: 8,
    description:
        "Embrace casual charm with our Denim Shirt, tailored for the modern woman who values comfort and style.",
    features: ["Button Down Front", "Chest Pockets", "Classic Collar", "100% Cotton"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Light Blue", "Dark Blue", "Black", "White"],
    category: "Women",
    brand: "Trendify",
    sku: "TRF-014",
    inStock: true,
    stockCount: 52,
    isNew: false,
    isSale: true,
  },
  {
    index: 14,
    id: "15",
    name: "Classic Polo Shirt with Contrast Collar and Cuffs",
    image: product_15,
    images: ["/images/product_15.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 120.0,
    rating: 4.2,
    reviews: 15,
    description: "A timeless classic with modern touches, perfect for casual and semi-formal occasions.",
    features: ["Contrast Collar", "Contrast Cuffs", "Three Button Placket", "Cotton Blend"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Navy", "Pink", "Light Blue"],
    category: "Women",
    brand: "Trendify",
    sku: "TRF-015",
    inStock: true,
    stockCount: 38,
    isNew: true,
    isSale: false,
  },
  {
    index: 15,
    id: "16",
    name: "Chic Handbag with Gold Hardware and Removable Strap",
    image: product_16,
    images: ["/images/product_16.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 140.0,
    originalPrice: 175.0,
    rating: 4.5,
    reviews: 9,
    description: "Complete your look with our Handbag, designed to be both stylish and functional for everyday use.",
    features: ["Gold Hardware", "Removable Strap", "Multiple Compartments", "Premium Material"],
    sizes: ["One Size"],
    colors: ["Black", "Brown", "Tan", "Navy"],
    category: "Women",
    brand: "Trendify",
    sku: "TRF-016",
    inStock: true,
    stockCount: 29,
    isNew: false,
    isSale: true,
  },
  {
    index: 16,
    id: "17",
    name: "Elegant Pointed Toe Stiletto Heels with Ankle Strap",
    image: product_17,
    images: ["/images/product_17.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 180.0,
    rating: 4.5,
    reviews: 11,
    description: "Step out in confidence with our Heels, crafted for comfort and style to elevate your every step.",
    features: ["Pointed Toe", "Stiletto Heel", "Ankle Strap", "Cushioned Insole"],
    sizes: ["6", "7", "8", "9", "10", "11"],
    colors: ["Black", "Nude", "Red", "Navy"],
    category: "Women",
    brand: "Trendify",
    sku: "TRF-017",
    inStock: true,
    stockCount: 33,
    isNew: true,
    isSale: false,
  },
  {
    index: 17,
    id: "18",
    name: "Stylish Hooded Winter Coat with Faux Fur Trim",
    image: product_18,
    images: ["/images/product_18.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 150.0,
    originalPrice: 190.0,
    rating: 4.5,
    reviews: 15,
    description:
        "Stay warm and stylish with our Winter Coat, crafted for the modern woman who values both fashion and function.",
    features: ["Hooded Design", "Faux Fur Trim", "Insulated Lining", "Water Resistant"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Gray", "Burgundy"],
    category: "Women",
    brand: "Trendify",
    sku: "TRF-018",
    inStock: true,
    stockCount: 26,
    isNew: false,
    isSale: true,
  },
  {
    index: 18,
    id: "19",
    name: "Premium Leather Crossbody Bag with Chain Detail",
    image: product_19,
    images: ["/images/product_19.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 195.0,
    rating: 4.6,
    reviews: 12,
    description:
        "Elevate your style with our premium crossbody bag, featuring elegant chain detail and luxurious leather.",
    features: ["Premium Leather", "Chain Detail", "Adjustable Strap", "Multiple Compartments"],
    sizes: ["One Size"],
    colors: ["Black", "Brown", "Burgundy", "Navy"],
    category: "Women",
    brand: "Trendify",
    sku: "TRF-019",
    inStock: true,
    stockCount: 18,
    isNew: true,
    isSale: false,
  },
  {
    index: 19,
    id: "20",
    name: "Fashionable Silk Scarf with Floral Print",
    image: product_20,
    images: ["/images/product_20.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 180.0,
    rating: 4.5,
    reviews: 14,
    description: "Complete your look with our Scarf, designed to add a touch of elegance to any outfit.",
    features: ["100% Silk", "Floral Print", "Versatile Styling", "Soft Texture"],
    sizes: ["One Size"],
    colors: ["Floral Blue", "Floral Pink", "Floral Green", "Solid Navy"],
    category: "Women",
    brand: "Trendify",
    sku: "TRF-020",
    inStock: true,
    stockCount: 31,
    isNew: true,
    isSale: false,
  },
  {
    index: 20,
    id: "21",
    name: "Elegant Pointed Toe Pumps with Kitten Heel",
    image: product_21,
    images: ["/images/product_21.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 80.0,
    originalPrice: 100.0,
    rating: 4.5,
    reviews: 10,
    description: "Step out in style with our Pumps, crafted for both comfort and sophistication.",
    features: ["Pointed Toe", "Kitten Heel", "Slip-On Style", "Comfortable Fit"],
    sizes: ["6", "7", "8", "9", "10", "11"],
    colors: ["Black", "Nude", "Navy", "Brown"],
    category: "Women",
    brand: "Trendify",
    sku: "TRF-021",
    inStock: true,
    stockCount: 44,
    isNew: false,
    isSale: true,
  },
  {
    index: 21,
    id: "22",
    name: "Classic Fit Two Button Wool Blend Suit",
    image: product_22,
    images: ["/images/product_22.png", "/images/hero2.jpg", "/images/hero3.jpg"],
    price: 240.0,
    rating: 4.5,
    reviews: 16,
    description:
        "Make a statement of bold elegance with our Suit, perfect for those who appreciate fashion that speaks volumes.",
    features: ["Two Button Style", "Wool Blend", "Classic Fit", "Professional Cut"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Gray", "Charcoal"],
    category: "Women",
    brand: "Trendify",
    sku: "TRF-022",
    inStock: true,
    stockCount: 37,
    isNew: true,
    isSale: false,
  },
]

export const featured_products = all_products.slice(0, 8)
export const new_arrivals = all_products.slice(8, 16)
